let activeTab=null;let scrollHeight=0;document.addEventListener("DOMContentLoaded",function(){resizeWindow();});function resizeWindow(){if(window.innerWidth<1024){scrollHeight=60;}else{scrollHeight=224;}
window.addEventListener("resize",function(){if(window.innerWidth<1024){scrollHeight=60;}else{scrollHeight=224;}});}
function fixErrorImage(){let images=document.getElementsByTagName("img");let imageCount=images.length;for(let i=0;i<imageCount;i++){images[i].addEventListener('error',function(event){const source=images[i].previousElementSibling;const isSource=source&&source.tagName==="SOURCE";if(isSource){const isMinWith=source.media.includes("min-width");const isMaxWith=source.media.includes("max-width");if(isMinWith){const width=parseInt(source.media.split("min-width:")[1].trim().split("px")[0]);if(window.innerWidth<width){event.target.src="https://d1jaw36n824swc.cloudfront.net/pictures_mid/600icons-2.png";event.target.srcset="https://d1jaw36n824swc.cloudfront.net/pictures_mid/600icons-2.png";event.onerror=null;}else{source.srcset="https://d1jaw36n824swc.cloudfront.net/pictures_mid/600icons-2.png";event.onerror=null;}}else if(isMaxWith){const width=parseInt(source.media.split("max-width:")[1].trim().split("px")[0]);if(window.innerWidth>width){event.target.src="https://d1jaw36n824swc.cloudfront.net/pictures_mid/600icons-2.png";event.target.srcset="https://d1jaw36n824swc.cloudfront.net/pictures_mid/600icons-2.png";event.onerror=null;}else{source.srcset="https://d1jaw36n824swc.cloudfront.net/pictures_mid/600icons-2.png";event.onerror=null;}}}else{event.target.src="https://d1jaw36n824swc.cloudfront.net/pictures_mid/600icons-2.png";event.target.srcset="https://d1jaw36n824swc.cloudfront.net/pictures_mid/600icons-2.png";event.onerror=null;}},false);}}
async function getData(request_type,discount_id){const params=new URLSearchParams({request_type:request_type,discount_id:discount_id,}).toString();return await fetch(`lib/ajax/discount.php?username=${shopName}&${params}`,{method:"POST",headers:{"Content-Type":"application/json",},body:localStorage.getItem("discountStorage"),});}
function toggleLoadingAnimation(action="show",section="#discount-loading-section"){let discountLoadingSection=document.querySelector(section);if(action==="show"){discountLoadingSection?.classList.remove("d-none");}else if(action==="hide"){setTimeout(()=>{discountLoadingSection?.classList.add("d-none");},300);}}
document.querySelector("#discount-add-tab")?.addEventListener("click",async function(){activeTab="addable";document.querySelector("#discount-loading-section")?.classList.remove("d-none");document.querySelector("#addable-discount-products-section")?.classList.remove("d-none");document.querySelector("#discount-add-tab .xy-discount-tabs-link").classList.add("active");document.querySelector("#addable-discount-categories-section")?.classList.remove("d-none");document.querySelector("#addable-discount-total-products")?.classList.remove("d-none");document.querySelector("#earnable-discount-products-section")?.classList.add("d-none");document.querySelector("#discount-earn-tab .xy-discount-tabs-link").classList.remove("active");document.querySelector("#earnable-discount-categories-section")?.classList.add("d-none");document.querySelector("#earnable-discount-total-products")?.classList.add("d-none");document.querySelector("#discount-loading-section")?.classList.add("d-none");lineActions(10);});document.querySelector("#discount-earn-tab")?.addEventListener("click",async function(){activeTab="earnable";document.querySelector("#discount-loading-section")?.classList.remove("d-none");document.querySelector("#earnable-discount-products-section")?.classList.remove("d-none");document.querySelector("#discount-earn-tab .xy-discount-tabs-link").classList.add("active");if(document.querySelector("#earnable-discount-categories-section").classList.contains("visible")){document.querySelector("#earnable-discount-categories-section").classList.remove("d-none");}
document.querySelector("#earnable-discount-total-products")?.classList.remove("d-none");document.querySelector("#addable-discount-products-section")?.classList.add("d-none");document.querySelector("#discount-add-tab .xy-discount-tabs-link")?.classList.remove("active");document.querySelector("#addable-discount-categories-section")?.classList.add("d-none");document.querySelector("#addable-discount-total-products")?.classList.add("d-none");document.querySelector("#discount-loading-section")?.classList.add("d-none");lineActions(10);});document.querySelectorAll("#discount-bar").forEach(function(el){let closeButton=el.querySelector("button[data-dismiss='alert']");let span=closeButton?.querySelector("span");el.addEventListener('click',function(event){if(event.target!==closeButton&&event.target!==span){openDiscountPanel(event,el);}else{el.remove();}});});document.querySelectorAll("#info-toast").forEach(function(el){let closeButton=el?.querySelector("#ajax-close-button");let span=closeButton?.querySelector("span");el.addEventListener('click',function(event){console.log("clicked");if(event.target!==closeButton&&event.target!==span){openDiscountPanel(event,el);}});});async function openDiscountPanel(e,el){let clickable=el.getAttribute("data-clickable");if(clickable==="false"){return;}
let redirectURL=el.getAttribute("data-redirect-url");const closeButton=el.querySelector("button");if(redirectURL&&redirectURL!=="#"){window.location.href=redirectURL;return;}
if(closeButton.contains(el.target)){return;}
offCanvasShow(el);productCardController();document.querySelector("#addable-discount-categories-section")?.classList.add("d-none");document.querySelector("#earnable-discount-categories-section")?.classList.add("d-none");toggleLoadingAnimation("show");toggleLoadingAnimation("show","#discount-categories-loading-section");let discountId=el.getAttribute("data-discount-id");let discountStorage={discount_id:discountId,addable_product:{listing_features:{offset:0,total:0,sorting:{status:false},filtering:{status:false},search:{status:false},load_more:{status:false,method:"all"},},},earnable_product:{listing_features:{offset:0,total:0,sorting:{status:false},filtering:{status:false},search:{status:false},load_more:{status:false,method:"all"},},},};localStorage.setItem("discountStorage",JSON.stringify(discountStorage));let data=await getData("get_discount",discountId).then((response)=>response.json());document.querySelector("#discount-canvas-notification-message").innerHTML=data["discount_canvas_notification_message"];if(data["addable_data"]&&data["show_discount_addable_section"]){listProduct("clear","addable",data["addable_data"]["category_data"],data["addable_data"]["product_data"],data["discount_all_text"]);}
if(data["earnable_data"]&&data["show_discount_earnable_section"]){listProduct("clear","earnable",data["earnable_data"]["category_data"],data["earnable_data"]["product_data"],data["discount_all_text"]);}
toggleLoadingAnimation("hide");toggleLoadingAnimation("hide","#discount-categories-loading-section");if(data["show_discount_addable_section"]){activeTab="addable";if(data["addable_data"]["category_data"]){setTimeout(()=>{document.querySelector("#addable-discount-categories-section")?.classList.remove("d-none");},300);}
document.querySelector("#addable-discount-products-section")?.classList.remove("d-none");document.querySelector("#addable-discount-total-products")?.classList.remove("d-none");document.querySelector("#earnable-discount-products-section")?.classList.add("d-none");if(!data["show_discount_tabs"]){document.querySelector(".xy-discount-tabs").classList.add("d-none");}}else{document.querySelector(".xy-discount-tabs").classList.add("d-none");}
let tempEarnableCategoryData=data["earnable_data"]["category_data"];let tempEarnableCategoryDataCount=null;let tempAddableCategoryData=data["addable_data"]["category_data"];let tempAddableCategoryDataCount=null;if(tempEarnableCategoryData!=undefined){tempEarnableCategoryDataCount=Object.keys(tempEarnableCategoryData).length;}
if(tempAddableCategoryData!=undefined){tempAddableCategoryDataCount=Object.keys(tempAddableCategoryData).length;}
document.querySelector("#earnable-discount-categories-section").classList.remove("visible");if(tempEarnableCategoryDataCount>0){document.querySelector("#earnable-discount-categories-section")?.classList.add("visible");}
document.querySelector("#addable-discount-categories-section").classList.remove("visible");if(tempAddableCategoryDataCount>0){document.querySelector("#addable-discount-categories-section")?.classList.add("visible");}
if(data["show_discount_earnable_section"]&&!data["show_discount_addable_section"]){activeTab="earnable";if(data["earnable_data"]["category_data"]){setTimeout(()=>{document.querySelector("#earnable-discount-categories-section")?.classList.remove("d-none");},300);}
document.querySelector("#earnable-discount-products-section")?.classList.remove("d-none");document.querySelector("#earnable-discount-total-products")?.classList.remove("d-none");document.querySelector("#addable-discount-products-section")?.classList.add("d-none");if(!data["show_discount_tabs"]){document.querySelector(".xy-discount-tabs").classList.add("d-none");}}
if(!(data["addable_data"]["category_data"]||data["earnable_data"]["category_data"])){document.querySelector('#discount-categories-sections').classList.add('d-none');}
attachDiscountCategoryChipEvent();infiniteScroll();fixErrorImage();}
function attachDiscountCategoryChipEvent(){let discountCategoryButtons=document.querySelectorAll(".discount-category-chip");discountCategoryButtons.forEach(function(button){button.addEventListener("click",async function(){toggleLoadingAnimation("show");let discountChipType=this.getAttribute("data-discount-chip-type");let discountCategoryId=parseInt(this.getAttribute("data-discount-category-id"));let discountStorage=JSON.parse(localStorage.getItem("discountStorage"));if(discountChipType==="addable"){discountStorage.addable_product.listing_features.load_more.status=true;discountStorage.addable_product.listing_features.load_more.method="by_category";discountStorage.addable_product.listing_features.load_more.category_id=discountCategoryId;discountStorage.addable_product.listing_features.offset=0;document.querySelector("#addable-discount-products-section")?.classList.add("d-none");}
if(discountChipType==="earnable"){discountStorage.earnable_product.listing_features.load_more.status=true;discountStorage.earnable_product.listing_features.load_more.method="by_category";discountStorage.earnable_product.listing_features.load_more.category_id=discountCategoryId;discountStorage.earnable_product.listing_features.offset=0;document.querySelector("#earnable-discount-products-section")?.classList.add("d-none");}
let discountId=discountStorage.discount_id;localStorage.setItem("discountStorage",JSON.stringify(discountStorage));let requestType=(discountChipType==="addable")?"get_discount_product_for_add":"get_discount_product_for_earn";let data=await getData(requestType,discountId).then((response)=>response.json());if(data["addable_data"]){listProduct("clear","addable",data["addable_data"]["category_data"],data["addable_data"]["product_data"]);}
if(discountChipType==="earnable"){listProduct("clear","earnable",data["earnable_data"]["category_data"],data["earnable_data"]["product_data"]);}
let selectedCategoryElement=document.querySelector('[data-discount-chip-type="'+discountChipType+'"].active');if(selectedCategoryElement){selectedCategoryElement.classList.remove("active");}
document.querySelector('[data-discount-chip-type="'+discountChipType+
'"][data-discount-category-id="'+discountCategoryId+'"]').classList.add("active");toggleLoadingAnimation("hide");setTimeout(()=>{if(data["addable_data"]){document.querySelector("#addable-discount-products-section")?.classList.remove("d-none");}
if(discountChipType==="earnable"){document.querySelector("#earnable-discount-products-section")?.classList.remove("d-none");}},300);});});}
function listProduct(mode="clear",sectionType="",categoryData=null,productData=null,allText=null){let discountStorage=JSON.parse(localStorage.getItem("discountStorage"));const{total}=productData["pagination"];let categorySectionSelector,totalProductSelector,productSectionSelector;if(sectionType==="addable"){categorySectionSelector="#addable-discount-categories-section";totalProductSelector="#addable-discount-total-products";productSectionSelector="#addable-discount-products-section";discountStorage.addable_product.listing_features.total=total;}else{categorySectionSelector="#earnable-discount-categories-section";totalProductSelector="#earnable-discount-total-products";productSectionSelector="#earnable-discount-products-section";discountStorage.earnable_product.listing_features.total=total;}
localStorage.setItem("discountStorage",JSON.stringify(discountStorage));if(allText!==null){localStorage.setItem("discountAllText",allText);}
if(categoryData){let offcanvasDiscountCategoriesSection=document.querySelector(categorySectionSelector);allText=localStorage.getItem("discountAllText");const categories=categoryData.categories;offcanvasDiscountCategoriesSection.innerHTML="";let categoriesLength=Object.keys(categories).length;let categoryTemplate='';let activeClass='active';if(categoriesLength>1){activeClass='';categoryTemplate=`<button type="button" 
            class="xy-discount-btn xy-discount-btn-chips xy-discount-btn-chips-primary discount-category-chip active"
            data-discount-chip-type="${sectionType}" data-discount-category-id="0"><div>${allText}</div></button>`;}
offcanvasDiscountCategoriesSection.innerHTML+=categoryTemplate;for(const categoryId in categories){categoryTemplate=`<button type="button" 
                class="xy-discount-btn xy-discount-btn-chips xy-discount-btn-chips-primary discount-category-chip ${activeClass}"
                data-discount-chip-type="${sectionType}" data-discount-category-id="${categoryId}">
                    <div>${categories[categoryId]}</div>
                </button>`;offcanvasDiscountCategoriesSection.innerHTML+=categoryTemplate;}}
document.querySelector(totalProductSelector).textContent=productData.pagination.total_text;let offcanvasDiscountProductsSection=document.querySelector(productSectionSelector);let offcanvasDiscountProductsSectionContent=offcanvasDiscountProductsSection.querySelector(`${productSectionSelector}-content`)
if(mode==="clear"){offcanvasDiscountProductsSectionContent.innerHTML="";}
productData.products.forEach((item)=>{let selfDiscountedLabelTemplate=``;if(item.is_self_discounted===true){if(item.discount_label_type==="discounted_product"){selfDiscountedLabelTemplate=`<span class="xy-discount-badge xy-discount-badge-danger">%${item.discount_label_rate} ${item.discount_label_text}</span>`;}}
let productLabelTemplate=``;if(item.label!==null){productLabelTemplate=`<span class="xy-discount-badge xy-discount-badge-light xy-discount-badge-bordered">${item.label_text}</span>`;}
let productLabelSectionTemplate=``;if(item.label!==null||item.is_self_discounted===true){productLabelSectionTemplate=`
                 <div class="xy-discount-card-product-other">
                    ${selfDiscountedLabelTemplate}
                    ${productLabelTemplate}
                </div>`;}
let priceTemplate;if(item.is_self_discounted===true){if(item.price.price_code==="TL"){let centTemplate=item.price.has_cent?`<span class="xy-discount-price-cent">${item.price.price_cent}</span>`:``;let originalPriceCentTemplate=item.original_price.has_cent?`<span class="xy-discount-price-cent">${item.original_price.price_cent}</span>&nbsp;`:``;priceTemplate=`<div class="xy-discount-price xy-discount-price-current">
                    <span class="xy-discount-price-value">${item.price.price_without_cent}</span>${centTemplate}&nbsp;<span class="xy-discount-price-currency">${item.price.price_code}</span>
                </div>
                <div class="xy-discount-price xy-discount-price-old">
                    <span class="xy-discount-price-value">${item.original_price.price_without_cent}</span>${originalPriceCentTemplate}&nbsp;<span class="xy-discount-price-currency">${item.original_price.price_code}</span></span>
                </div>`;}else{let centTemplate=item.price.has_cent?`<span class="xy-discount-price-cent">${item.price.price_cent}</span>&nbsp;`:``;let originalPriceCentTemplate=item.original_price.has_cent?`<span class="xy-discount-price-cent">${item.original_price.price_cent}</span>&nbsp;`:``;priceTemplate=`<div class="xy-discount-price xy-discount-price-current">
                        <span class="xy-discount-price-value">${item.price.price_symbol} ${item.price.price_without_cent}</span>${centTemplate}
                    </div>
                    <div class="xy-discount-price xy-discount-price-old">
                        <span class="xy-discount-price-value">${item.original_price.price_symbol} ${item.original_price.price_without_cent}</span>${originalPriceCentTemplate}
                    </div>`;}}else{if(item.price.price_code==="TL"){let centTemplate=item.price.has_cent?`<span class="xy-discount-price-cent">${item.price.price_cent}</span>`:``;priceTemplate=`<div class="xy-discount-price xy-discount-price-current">
                    <span class="xy-discount-price-value">${item.price.price_without_cent}</span>${centTemplate}&nbsp;<span class="xy-discount-price-currency">${item.price.price_code}</span>
                </div>`;}else{let centTemplate=item.price.has_cent?`<span class="xy-discount-price-cent">${item.price.price_cent}</span>&nbsp;`:``;priceTemplate=`<div class="xy-discount-price xy-discount-price-current">
                    <span class="xy-discount-price-value">${item.price.price_symbol} ${item.price.price_without_cent}</span>${centTemplate}
                </div>`;}}
let cardEl=document.createElement("div");cardEl.classList.value="xy-discount-card xy-discount-card-product";cardEl.innerHTML=`
                            <a href="${item.link}">
                            <div class="xy-discount-card-header">
                                <div class="xy-discount-card-img-container">
                                    <picture>
                                        <source media="(min-width: 1024px)" srcset="${item.image_prefix}${item.image_endpoints.large}${item.image}">
                                        <img src="${item.image_prefix}${item.image_endpoints.mid}${item.image}" class="xy-discount-card-img" alt="${item.name}" loading="lazy" 
                                    </picture>
                                </div>
                            </div>
                            <div class="xy-discount-card-body">
                                ${productLabelSectionTemplate}
                                <div class="xy-discount-card-product-name">
                                    <div>
                                        ${item.name}
                                    </div>
                                </div>
                                <div class="xy-discount-card-product-price word-break">
                                   ${priceTemplate}
                                </div>
                            </div>
                            </a>`;offcanvasDiscountProductsSectionContent.appendChild(cardEl);});lineActions(1001);attachDiscountCategoryChipEvent();}
const fetchScrollData=async(type,request_type,id)=>{return await getData(request_type,id).then((res)=>res.json()).then((data)=>{if(data){listProduct("update",type,data[`${type}_data`]["category_data"],data[`${type}_data`]["product_data"]);}});};function infiniteScroll(sectionType="",offset=0,total=0){let body=document.querySelector(".xy-discount-offcanvas-body");let isScrolling=false;let productCount=16;resizeWindow();body?.addEventListener("scroll",async()=>{sectionType=activeTab;let discountStorage=JSON.parse(localStorage.getItem("discountStorage"));if(sectionType==="addable"){offset=discountStorage.addable_product.listing_features.offset;total=discountStorage.addable_product.listing_features.total;}else{offset=discountStorage.earnable_product.listing_features.offset;total=discountStorage.earnable_product.listing_features.total;}
let discountId=discountStorage.discount_id;let requestType=(sectionType==="addable")?"get_discount_product_for_add":"get_discount_product_for_earn";if(body.scrollHeight-body.scrollTop<=body.clientHeight+scrollHeight){if(isScrolling){return;}
if(offset+productCount<total){if(sectionType==="addable"){discountStorage.addable_product.listing_features.offset+=productCount;}
if(sectionType==="earnable"){discountStorage.earnable_product.listing_features.offset+=productCount;}
localStorage.setItem("discountStorage",JSON.stringify(discountStorage));isScrolling=true;try{showTempProductLoading(sectionType);await fetchScrollData(sectionType,requestType,discountId);setTimeout(async function(){hideTempProductLoading(sectionType);},300);}finally{isScrolling=false;}}}});}
function showTempProductLoading(sectionType){let loadingTemplate=`<div class="xy-discount-card xy-discount-card-product xy-discount-card-placeholder temp_loading">
            <div class="xy-discount-card-header">
                <div class="xy-discount-card-img-container"></div>
            </div>
            <div class="xy-discount-card-body">
                <div class="xy-discount-card-product-name"></div>
                <div class="xy-discount-card-product-price"></div>
            </div>
        </div>`;let templatesArray=Array.from({length:32},()=>loadingTemplate);let cardEl=document.createElement("div");cardEl.classList.value="temp_loading";document.querySelector('#'+sectionType+'-discount-products-section-content').innerHTML+=templatesArray.join('');}
function hideTempProductLoading(){let tempLoadingElements=document.querySelectorAll(".temp_loading");tempLoadingElements.forEach(element=>{element.remove();});}
let deferredDiscountNotification=document.querySelectorAll('#defer-discount-notification');deferredDiscountNotification?.forEach(function(el){el.addEventListener('click',function(){fetch(`lib/ajax/discount.php?request_type=defer_discount_notification&username=${shopName}`,{method:"GET",headers:{"Content-Type":"application/json",}}).then(r=>r.json());});});function lineActions(time){let size=14;const action=setInterval(()=>{let buttons=document.querySelectorAll(".xy-discount-btn-chips:not(.xy-discount-btn-placeholder)");buttons.forEach((btn)=>{let div=btn.querySelector("div");if(!btn.classList.contains("line-1")){if(div?.clientHeight>=size&&div?.clientHeight<size*2){btn.classList.add("line-1");}
clearInterval(action);}});},time);}